# $Id$

################################################################################
# The make rule compiles the code for DUT and Tester
################################################################################
all:
	make -f Makefile.DUT
	make -f Makefile.Tester

clean:
	make -f Makefile.DUT clean
	make -f Makefile.Tester clean

cleanall:
	make -f Makefile.DUT cleanall
	make -f Makefile.Tester cleanall
