/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"

juce_ImplementSingleton (BlmProperties)

class BlmWindow
    : public DocumentWindow
{
public:

    //==============================================================================
    BlmWindow() 
      : DocumentWindow ("MIDIbox BLM16x16+X Emulation",
			Colours::lightgrey,
			DocumentWindow::allButtons,
			true)
    {
        MainComponent* const contentComponent = new MainComponent();
        setContentComponent (contentComponent, true, true);
        setUsingNativeTitleBar(true);
        centreWithSize (getWidth(), getHeight());

        setVisible (true);
    }

    ~BlmWindow()
    {
        // (the content component will be deleted automatically, so no need to do it here)
    }

    //==============================================================================
    void closeButtonPressed()
    {
        // When the user presses the close button, we'll tell the app to quit. This 
        // window will be deleted by our MiosStudioApplication::shutdown() method
        // 
        JUCEApplication::quit();
    }
};



//==============================================================================
class BLMApplication  : public JUCEApplication
{
public:
    //==============================================================================
    BLMApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    BlmWindow* blmWindow;

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // just create the main window...
        blmWindow = new BlmWindow();
    }

    void shutdown()
    {
        // Add your application's shutdown code here..
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (BLMApplication)
