/*
 *  ACFreqOfNote.h
 *  kII
 *
 *  Created by Michael Markert, audiocommander on 25.11.06
 *
 *  Copyright 2006 Michael Markert, http://www.audiocommander.de
 *
 */

/*
 * Released under GNU General Public License
 * http://www.gnu.org/licenses/gpl.html
 * 
 * This program is free software; you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation
 *
 * YOU ARE ALLOWED TO COPY AND CHANGE 
 * BUT YOU MUST RELEASE THE SOURCE TOO (UNDER GNU GPL) IF YOU RELEASE YOUR PRODUCT 
 * YOU ARE NOT ALLOWED TO USE IT WITHIN PROPRIETARY CLOSED-SOURCE PROJECTS
 */


#ifndef ACFREQOFNOTE_H
#define ACFREQOFNOTE_H


#include "ACMidiDefines.h"


// global freqOfNote
extern const unsigned int freqOfNote[128];

// returns the freq in Hz for notes 0..127
// FREQUENCY (in Hertz) = 440 * 2 ^ ( (OCTAVE - 4) + ((TON - 10) / 12) )
const unsigned int freqOfNote[128] = {
	MIDI_NOTE_0_FREQ, MIDI_NOTE_1_FREQ, MIDI_NOTE_2_FREQ, MIDI_NOTE_3_FREQ, MIDI_NOTE_4_FREQ, 
	MIDI_NOTE_5_FREQ, MIDI_NOTE_6_FREQ, MIDI_NOTE_7_FREQ, MIDI_NOTE_8_FREQ, MIDI_NOTE_9_FREQ, 
	MIDI_NOTE_10_FREQ, MIDI_NOTE_11_FREQ, MIDI_NOTE_12_FREQ, MIDI_NOTE_13_FREQ, MIDI_NOTE_14_FREQ, 
	MIDI_NOTE_15_FREQ, MIDI_NOTE_16_FREQ, MIDI_NOTE_17_FREQ, MIDI_NOTE_18_FREQ, MIDI_NOTE_19_FREQ, 
	MIDI_NOTE_20_FREQ, MIDI_NOTE_21_FREQ, MIDI_NOTE_22_FREQ, MIDI_NOTE_23_FREQ, MIDI_NOTE_24_FREQ, 
	MIDI_NOTE_25_FREQ, MIDI_NOTE_26_FREQ, MIDI_NOTE_27_FREQ, MIDI_NOTE_28_FREQ, MIDI_NOTE_29_FREQ, 
	MIDI_NOTE_30_FREQ, MIDI_NOTE_31_FREQ, MIDI_NOTE_32_FREQ, MIDI_NOTE_33_FREQ, MIDI_NOTE_34_FREQ, 
	MIDI_NOTE_35_FREQ, MIDI_NOTE_36_FREQ, MIDI_NOTE_37_FREQ, MIDI_NOTE_38_FREQ, MIDI_NOTE_39_FREQ, 
	MIDI_NOTE_40_FREQ, MIDI_NOTE_41_FREQ, MIDI_NOTE_42_FREQ, MIDI_NOTE_43_FREQ, MIDI_NOTE_44_FREQ, 
	MIDI_NOTE_45_FREQ, MIDI_NOTE_46_FREQ, MIDI_NOTE_47_FREQ, MIDI_NOTE_48_FREQ, MIDI_NOTE_49_FREQ, 
	MIDI_NOTE_50_FREQ, MIDI_NOTE_51_FREQ, MIDI_NOTE_52_FREQ, MIDI_NOTE_53_FREQ, MIDI_NOTE_54_FREQ, 
	MIDI_NOTE_55_FREQ, MIDI_NOTE_56_FREQ, MIDI_NOTE_57_FREQ, MIDI_NOTE_58_FREQ, MIDI_NOTE_59_FREQ, 
	MIDI_NOTE_60_FREQ, MIDI_NOTE_61_FREQ, MIDI_NOTE_62_FREQ, MIDI_NOTE_63_FREQ, MIDI_NOTE_64_FREQ, 
	MIDI_NOTE_65_FREQ, MIDI_NOTE_66_FREQ, MIDI_NOTE_67_FREQ, MIDI_NOTE_68_FREQ, MIDI_NOTE_69_FREQ, 
	MIDI_NOTE_70_FREQ, MIDI_NOTE_71_FREQ, MIDI_NOTE_72_FREQ, MIDI_NOTE_73_FREQ, MIDI_NOTE_74_FREQ, 
	MIDI_NOTE_75_FREQ, MIDI_NOTE_76_FREQ, MIDI_NOTE_77_FREQ, MIDI_NOTE_78_FREQ, MIDI_NOTE_79_FREQ, 
	MIDI_NOTE_80_FREQ, MIDI_NOTE_81_FREQ, MIDI_NOTE_82_FREQ, MIDI_NOTE_83_FREQ, MIDI_NOTE_84_FREQ, 
	MIDI_NOTE_85_FREQ, MIDI_NOTE_86_FREQ, MIDI_NOTE_87_FREQ, MIDI_NOTE_88_FREQ, MIDI_NOTE_89_FREQ, 
	MIDI_NOTE_90_FREQ, MIDI_NOTE_91_FREQ, MIDI_NOTE_92_FREQ, MIDI_NOTE_93_FREQ, MIDI_NOTE_94_FREQ, 
	MIDI_NOTE_95_FREQ, MIDI_NOTE_96_FREQ, MIDI_NOTE_97_FREQ, MIDI_NOTE_98_FREQ, MIDI_NOTE_99_FREQ, 
	MIDI_NOTE_100_FREQ, MIDI_NOTE_101_FREQ, MIDI_NOTE_102_FREQ, MIDI_NOTE_103_FREQ, MIDI_NOTE_104_FREQ, 
	MIDI_NOTE_105_FREQ, MIDI_NOTE_106_FREQ, MIDI_NOTE_107_FREQ, MIDI_NOTE_108_FREQ, MIDI_NOTE_109_FREQ,
	MIDI_NOTE_110_FREQ, MIDI_NOTE_111_FREQ, MIDI_NOTE_112_FREQ, MIDI_NOTE_113_FREQ, MIDI_NOTE_114_FREQ,
	MIDI_NOTE_115_FREQ, MIDI_NOTE_116_FREQ, MIDI_NOTE_117_FREQ, MIDI_NOTE_118_FREQ, MIDI_NOTE_119_FREQ, 
	MIDI_NOTE_120_FREQ, MIDI_NOTE_121_FREQ, MIDI_NOTE_122_FREQ, MIDI_NOTE_123_FREQ, MIDI_NOTE_124_FREQ, 
	MIDI_NOTE_125_FREQ, MIDI_NOTE_126_FREQ, MIDI_NOTE_127_FREQ
};

#endif /* ACFREQOFNOTE_H */
